services:

  app:
    container_name: todo-frontend
    build:
      context: ./todo-frontend
      dockerfile: dev.Dockerfile
    depends_on:
      - backend
    environment:
      - VITE_BACKEND_URL=http://localhost:3000
    ports:
      - 5173:5173
    volumes:
      - ./todo-frontend:/usr/src/app

  backend:
    container_name: todo-backend
    build: ./todo-backend
    depends_on:
      - mongo
      - redis
    environment:
      - MONGO_URL=mongodb://the_username:the_password@mongo:27017/the_database
      - REDIS_URL=redis://redis:6379
    ports:
      - 3000:3000
    volumes:
      - ./todo-backend:/usr/src/app
    command: ["npm", "run", "dev"]

  mongo:
    container_name: todo-mongo
    image: mongo
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=example
      - MONGO_INITDB_DATABASE=the_database
    volumes:
      - ./todo-backend/mongo/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
      - mongo_data:/data/db

  redis:
    container_name: todo-redis
    image: redis
    ports:
      - 6379:6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - redis_data:/data

  nginx:
    container_name: todo-nginx
    depends_on:
      - app
    image: nginx:mainline-alpine
    ports:
      - 8080:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/nginx.conf:ro

volumes:
  mongo_data:
  redis_data:
